"""Pinned canonical schema definitions used by the package."""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import asdict, dataclass

BDS_SCHEMA_VERSION = "bds-2026-05"
BDF_SCHEMA_VERSION = "bdf-2026-05"
LEGACY_SCHEMA_VERSIONS = (BDF_SCHEMA_VERSION,)
SUPPORTED_SCHEMA_VERSIONS = (BDS_SCHEMA_VERSION, *LEGACY_SCHEMA_VERSIONS)


@dataclass(frozen=True)
class ColumnSpec:
    label: str
    machine_name: str
    unit: str
    required: bool = False
    description: str = ""
    aliases: tuple[str, ...] = ()


CANONICAL_COLUMNS: tuple[ColumnSpec, ...] = (
    ColumnSpec(
        "test_time_s",
        "test_time_s",
        "s",
        True,
        "Elapsed time since the start of the test.",
        (
            "Test Time / s",
            "test_time_second",
            "Test Time",
            "Test Time(s)",
            "Test Time (s)",
            "Total Time",
            "Total Time(s)",
            "TotalTime(s)",
            "TotalTime_S",
            "Testtime",
            "Testtime(s)",
            "TotTime(H:M:S)",
            "Programmdauer",
            "test_time",
            "Test_Time",
            "Time",
            "Time[s]",
            "Time(s)",
            "Time [s]",
            "time/s",
            "t_s",
            "Prog Time",
            "Program Time",
            "run_time",
            "Test (Sec)",
            "TestTime",
            "TestTime(s)",
            "Run Time",
            "Run Time (h)",
            "test_time_millisecond",
            "time (s)",
            "time__s",
            "h_test_time__s",
            "Time [hours]",
            "~Time[h]",
            "总时间(s)",
            "测试时间(s)",
        ),
    ),
    ColumnSpec(
        "voltage_v",
        "voltage_v",
        "V",
        True,
        "Instantaneous voltage.",
        (
            "Voltage / V",
            "voltage_volt",
            "Voltage",
            "Voltage(V)",
            "Voltage (V)",
            "Voltage [V]",
            "Voltage[V]",
            "Volts",
            "Potential[V]",
            "Potential(V)",
            "Potential (V)",
            "Ecell/V",
            "Ecell_V",
            "Ewe/V",
            "Ewe_V",
            "Ewe/V vs.",
            "c_vol",
            "<V>/V",
            "voltage_volt",
            "voltage__V",
            "h_potential__V",
            "U[V]",
            "U(V)",
            "U_Battery",
            "Channel Voltage",
            "voltage_V",
            "WE(1).Potential (V)",
            "Potential (V)",
            "V5 (mV)",
            "V5 (V)",
            "VB",
            "pack voltage(V)",
            "pack volage(V)",
            "电压(V)",
        ),
    ),
    ColumnSpec(
        "current_a",
        "current_a",
        "A",
        True,
        "Instantaneous current.",
        (
            "Current / A",
            "current_ampere",
            "Current",
            "Current(A)",
            "Current (A)",
            "Current [A]",
            "Current[A]",
            "Current(mA)",
            "Current (mA)",
            "Current[mA]",
            "Cur(mA)",
            "Amps",
            "I/A",
            "<I>/A",
            "I/mA",
            "<I>/mA",
            "c_cur",
            "current_ampere",
            "current__A",
            "h_current__A",
            "I[A]",
            "I(A)",
            "I_Battery",
            "I (A)",
            "Channel Current",
            "current_A",
            "WE(1).Current (A)",
            "current load",
            "电流(A)",
            "电流(mA)",
        ),
    ),
    ColumnSpec(
        "unix_time_s",
        "unix_time_s",
        "s",
        False,
        "UTC Unix timestamp.",
        (
            "Unix Time / s",
            "unix_time_second",
            "Unix Time",
            "Timestamp",
            "DateTime",
            "Datetime",
            "Date Time",
            "Date and Time",
            "Realtime",
            "Date",
            "sampling time",
        ),
    ),
    ColumnSpec(
        "date_time",
        "date_time",
        "",
        False,
        "ISO-8601 timestamp extension column.",
        (
            "Date Time ISO",
            "date_time_iso",
            "DateTime",
            "Datetime",
            "Date Time",
            "Date and Time",
            "Realtime",
            "Absolute Time",
            "DPt Time",
            "Date",
            "sampling time",
        ),
    ),
    ColumnSpec(
        "cycle_index",
        "cycle_index",
        "1",
        False,
        "Monotonically increasing cycle index.",
        (
            "Cycle Count / 1",
            "cycle_count",
            "Cycle Count",
            "Cycle",
            "Cycle ID",
            "Cycle_Index",
            "Cycle Index",
            "cycle_index",
            "Cyc#",
            "Cycle Number",
            "CurCycle",
            "Number_of_Cycle",
        ),
    ),
    ColumnSpec(
        "step_index",
        "step_index",
        "1",
        False,
        "Monotonically increasing step index.",
        (
            "Step Count / 1",
            "step_count",
            "Step Count",
            "Step",
            "Step ID",
            "Step_Index",
            "Step Index",
            "Step Number",
            "StepNo",
            "Ns",
        ),
    ),
    ColumnSpec(
        "record_index",
        "record_index",
        "1",
        False,
        "Point index within a step.",
        (
            "Step Index / 1",
            "Record Count / 1",
            "Record Index",
            "data_point_index",
            "DataPoint",
            "Data Point",
            "Record",
            "Record ID",
            "Record Index",
            "data_point",
            "Data_Point",
            "Rec#",
            "Record_number",
            "DataSequence",
        ),
    ),
    ColumnSpec(
        "step_time_s",
        "step_time_s",
        "s",
        False,
        "Elapsed time within the active step.",
        (
            "Step Time / s",
            "step_time_second",
            "Step Time",
            "Step (Sec)",
            "Step Time(s)",
            "Step_Time",
            "Step Time (s)",
            "Step Time (h)",
            "Time(s)",
            "Time(h:min:s.ms)",
            "StepTime(s)",
            "StepTime",
            "StepTime(H:M:S)",
            "step time/s",
            "State Time(s)",
            "Relative Time(s)",
            "Relative_Time_h_min_s.ms_",
            "t-Step[h]",
            "t-Set[h]",
            "时间(s)",
        ),
    ),
    ColumnSpec(
        "ambient_temperature_deg_c",
        "ambient_temperature_deg_c",
        "degC",
        False,
        "Ambient or chamber temperature.",
        (
            "Ambient Temperature / degC",
            "ambient_temperature_celsius",
            "Temperature",
            "Temperature(C)",
            "Temperature (C)",
            "Temperature(°C)",
            "Temperature[°C]",
            "Temperature/°C",
            "Temperature/Â°C",
            "Temperature [degC]",
            "Temperature 1 (degC)",
            "Aux_Temperature_1 (C)",
            "Aux_Temperature(C)_1",
            "Aux_Temperature(degC)_1",
            "Aux_Temperature(°C)_1",
            "Aux_Temperature(Â°C)_1",
            "Aux_Temperature(Ąć)_1",
            "Aux_Temperature(¡æ)_1",
            "Circuit Temperature (°C)",
            "c_temp",
            "c_surf_temp",
            "amb_temp",
            "Temp 1",
            "Temp(C)",
            "T/°C",
            "T1[°C]",
            "T1[degC]",
            "Temperature_1",
            "temperature_C",
            "TB",
            "Temp[1](C)",
            "温度(°C)",
        ),
    ),
    ColumnSpec(
        "temperature_t1_deg_c",
        "temperature_t1_deg_c",
        "degC",
        False,
        "Surface temperature sensor T1.",
        (
            "Surface Temperature T1 / degC",
            "temperature_t1_celsius",
            "T1",
            "Temperature 1",
            "Surface Temperature T1",
        ),
    ),
    ColumnSpec(
        "charge_capacity_ah",
        "charge_capacity_ah",
        "Ah",
        False,
        "Capacity accumulated during charge.",
        (
            "Charging Capacity / Ah",
            "charging_capacity_ah",
            "Charging Capacity (Ah)",
            "Charge Capacity",
            "Charge Capacity(Ah)",
            "Charge Capacity (Ah)",
            "Charge Capacity(mAh)",
            "Capacitance_Chg(mAh)",
            "Chg.Capacity(mAh)",
            "Charge_Capacity",
            "Charge_Capacity (Ah)",
            "Chg Capacity (Ah)",
            "Chg Capacity (AHr)",
            "Char. Cap.(Ah)",
            "KAPA_CC(Ah)",
            "KAPA_CV(Ah)",
            "Q charge/mA.h",
        ),
    ),
    ColumnSpec(
        "discharge_capacity_ah",
        "discharge_capacity_ah",
        "Ah",
        False,
        "Capacity accumulated during discharge.",
        (
            "Discharging Capacity / Ah",
            "discharging_capacity_ah",
            "Discharging Capacity (Ah)",
            "Discharge Capacity",
            "Discharge Capacity(Ah)",
            "Discharge Capacity (Ah)",
            "Discharge Capacity(mAh)",
            "Capacitance_DChg(mAh)",
            "DChg.Capacity(mAh)",
            "Discharge_Capacity",
            "Discharge_Capacity (Ah)",
            "DChg Capacity (Ah)",
            "DChg Capacity (AHr)",
            "Dischar. Cap.(Ah)",
            "Q discharge/mA.h",
        ),
    ),
    ColumnSpec(
        "charge_energy_wh",
        "charge_energy_wh",
        "Wh",
        False,
        "Energy accumulated during charge.",
        (
            "Charging Energy / Wh",
            "charging_energy_wh",
            "Charging Energy (Wh)",
            "Charge Energy",
            "Charge Energy(Wh)",
            "Charge Energy (Wh)",
            "Charge Energy(mWh)",
            "Engy_Chg(mWh)",
            "Charge_Energy",
            "Chg Energy (Wh)",
            "Chg Energy (WHr)",
        ),
    ),
    ColumnSpec(
        "discharge_energy_wh",
        "discharge_energy_wh",
        "Wh",
        False,
        "Energy accumulated during discharge.",
        (
            "Discharging Energy / Wh",
            "discharging_energy_wh",
            "Discharging Energy (Wh)",
            "Discharge Energy",
            "Discharge Energy(Wh)",
            "Discharge Energy (Wh)",
            "Discharge Energy(mWh)",
            "Engy_DChg(mWh)",
            "Discharge_Energy",
            "DChg Energy (Wh)",
            "DChg Energy (WHr)",
        ),
    ),
    ColumnSpec(
        "power_w",
        "power_w",
        "W",
        False,
        "Instantaneous power.",
        (
            "Power / W",
            "power_watt",
            "Power",
            "Power(W)",
            "Power (W)",
            "Power(mW)",
            "Power [W]",
            "P/W",
            "P(W)",
        ),
    ),
    ColumnSpec(
        "internal_resistance_ohm",
        "internal_resistance_ohm",
        "ohm",
        False,
        "Internal resistance.",
        (
            "Internal Resistance / ohm",
            "Internal Resistance",
            "Internal_Resistance",
            "DCIR(O)",
            "DCIR(Ω)",
            "DCIR/Ohms",
            "ACR (Ohm)",
            "ACImp/Ohms",
            "R/Ohm",
            "Rapp/Ohm",
            "IR",
            "AC_Impedance",
        ),
    ),
)

REQUIRED_COLUMNS = tuple(c.label for c in CANONICAL_COLUMNS if c.required)
OPTIONAL_COLUMNS = tuple(c.label for c in CANONICAL_COLUMNS if not c.required)
ALL_COLUMNS = tuple(c.label for c in CANONICAL_COLUMNS)
LABEL_TO_SPEC = {c.label: c for c in CANONICAL_COLUMNS}
MACHINE_TO_LABEL = {c.machine_name: c.label for c in CANONICAL_COLUMNS}
ALIAS_TO_LABEL = {
    str(alias).strip().lower(): c.label
    for c in CANONICAL_COLUMNS
    for alias in (c.label, c.machine_name, *c.aliases)
}


def schema_dict() -> dict:
    return {
        "schema_version": BDS_SCHEMA_VERSION,
        "legacy_schema_versions": list(LEGACY_SCHEMA_VERSIONS),
        "required": list(REQUIRED_COLUMNS),
        "columns": [asdict(c) for c in CANONICAL_COLUMNS],
    }


def aliases_for(label: str, extra: Iterable[str] = ()) -> tuple[str, ...]:
    spec = LABEL_TO_SPEC[label]
    return (spec.label, spec.machine_name, *spec.aliases, *tuple(extra))


def canonical_label_for(label: str) -> str | None:
    """Return the BDS canonical field name for a canonical field or legacy alias."""
    return ALIAS_TO_LABEL.get(str(label).strip().lower())
